import { ModalProvider } from '@/components/providers/modal-provider'
import './globals.css'
import type { Metadata } from 'next'
import { cn } from '@/lib/utils'
import { mainFont } from '@/lib/fonts'
import {myFont} from '@/lib/fonts'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(mainFont.className, "overflow-x-hidden font-normal")}>
        <ModalProvider />
        {children}
      </body>
    </html>
  );
}
